-- AlterTable
ALTER TABLE "Schedule" ALTER COLUMN "startTime" SET DATA TYPE TEXT,
ALTER COLUMN "endTime" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "WorkOrder" ALTER COLUMN "endHour" SET DATA TYPE TEXT,
ALTER COLUMN "startHour" SET DATA TYPE TEXT;
